### PR TITLE
conflict: append '-' to path if it's an add patch

### LINKED ISSUE #45: ADD_BACK_TO_HEAD should end `-` in the path when it is converted to a json-patch
My understanding is that `ADD_BACK_TO_HEAD` conflicts always points to a path and they mean that the value should be added to given array.

So this could better be represented with a path `/path/to/array/-` when it's converted to a json-patch.

https://tools.ietf.org/html/rfc6901#section-4
https://tools.ietf.org/html/rfc6902#appendix-A.16

### PR DESCRIPTION
**Pull request by harunurhan**
* Closes #45

### CODE REVIEW

**Comment by harunurhan** [comment]
Travis is failing because a code style rule that wasn't introduced in this PR!

**Comment by jacquerie** [comment]
> Travis is failing because a code style rule that wasn't introduced in this PR!

This is in fact https://github.com/inveniosoftware/troubleshooting/issues/15.

**Comment by jacquerie** [comment]
> This is in fact inveniosoftware/troubleshooting#15.

And https://github.com/inveniosoftware-contrib/json-merger/pull/47 fixed it, so if you rebase this it should work now.

**Comment by jacquerie** [comment]
Retouched a bit the commit message, because the link to the spec was too interesting not to be included!

**Pull request merged**
